spring.application.name=webi

spring.data.mongodb.uri=mongodb+srv://webi-user:webiGDG1@webi-cluster.okk289d.mongodb.net/webi-db?retryWrites=true&w=majority

# API server URL
api.server.url=https://api.webi.click

# AI server URL
ai.server.url=http://ai.webi.click:80/api/process-html-with-actions

# Swagger UI path
springdoc.swagger-ui.path=/docs

# socket URL
socket.url=http://chat.webi.click/users

# Chrome Extension URL
chrome.extension.url=chrome-extension://fbnieomeclcegpcicnbbfehclmppplnd

# Google OAuth settings


# Kakao OAuth settings
sns.kakao.url=https://kauth.kakao.com/oauth/authorize
sns.kakao.client.id=${KAKAO_CLIENT_ID}
sns.kakao.callback.url=https://api.webi.click/auth/kakao/callback
sns.kakao.token.url=https://kauth.kakao.com/oauth/token

# Naver OAuth settings
sns.naver.url=https://nid.naver.com/oauth2.0/authorize
sns.naver.client.id=${NAVER_CLIENT_ID}
sns.naver.client.secret=${NAVER_CLIENT_SECRET}
sns.naver.callback.url=https://api.webi.click/auth/naver/callback
sns.naver.token.url=https://nid.naver.com/oauth2.0/token

# UTF-8 encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# RabbitMQ settings
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=5671
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
#spring.rabbitmq.ssl.enabled=true