spring.application.name=webi

# DB ?? ??
spring.datasource.url=jdbc:postgresql://webi-postgres-db.c3mw42geutla.ap-northeast-2.rds.amazonaws.com:5432/webi_db
spring.datasource.username=webidb
spring.datasource.password=hongikGDG1!


# JPA ?? ??
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect