spring.application.name=webi

# DB setting
spring.datasource.url=jdbc:postgresql://webi-postgres-db.c3mw42geutla.ap-northeast-2.rds.amazonaws.com:5432/webi_db
spring.datasource.username=webidb
spring.datasource.password=hongikGDG1!

spring.data.mongodb.uri=mongodb+srv://webi-user:webiGDG1@webi-cluster.okk289d.mongodb.net/webi-db?retryWrites=true&w=majority

# JPA setting
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# AI server URL
ai.server.url=http://ai.webi.click:80/api/process-html

# socket URL
socket.url=http://chat.webi.click:80/users/:userId/message

# request ?? ?? ??(dafault 2MB)
server.tomcat.max-http-form-post-size=20MB